export const TECHSTACK_KEYS = {
  JAVASCRIPT: "Javascript",
  TYPESCRIPT: "Typescript",
  PHP: "PHP",
  REACT: "React",
  NEXTJS: "Next.js",
  REACT_NATIVE: "React Native",
  TAILWIND: "Tailwind CSS",
  MUI: "MUI",
  SHADCN: "Shadcn UI",
  JOTAI: "Jotai",
  REACT_HOOK_FORM: "React Hook Form",
  REDUX: "Redux",
  ZUSTAND: "Zustand",
  VITE: "Vite.js",
  TANSTACK_QUERY: "Tanstack Query",
  LARAVEL: "Laravel",
  EXPRESS: "Express.js",
  MYSQL: "Mysql",
  MOTION: "Motion",
};
